x-common-config: &common-config
  image: ghcr.io/shenmintao/nanobot:latest
  volumes:
    - ./data:/root/.nanobot

services:
  nanobot-gateway:
    container_name: nanobot-gateway
    <<: *common-config
    command: ["gateway"]
    restart: unless-stopped
    network_mode: host
    environment:
      - HTTP_PROXY=http://192.168.10.50:1080
      - HTTPS_PROXY=http://192.168.10.50:1080
      - NO_PROXY=localhost,127.0.0.1,192.168.0.0/16
 
  nanobot-cli:
    <<: *common-config
    profiles:
      - cli
    command: ["status"]
    stdin_open: true
    tty: true

  nanobot-bridge:
    image: ghcr.io/shenmintao/nanobot:latest
    container_name: nanobot-bridge
    volumes:
      - ./data:/root/.nanobot
    working_dir: /app/bridge
    entrypoint: []
    command: ["npm", "start"]
    restart: unless-stopped
    network_mode: host
    environment:
      - BRIDGE_PORT=3002
      - HTTP_PROXY=http://192.168.10.50:1080
      - HTTPS_PROXY=http://192.168.10.50:1080
      - NO_PROXY=localhost,127.0.0.1,192.168.0.0/16

